"""add search_vector e indice gin

Revision ID: 61b3e04d8aa6
Revises: 
Create Date: 2026-09-21 13:24:35.635420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61b3e04d8aa6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'links_pages', ['origin_id', 'destiny_id'])
    op.add_column('pages', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("\n            setweight(\n                to_tsvector('portuguese', coalesce(title, '')),\n                'A'\n            ) ||\n            setweight(\n                to_tsvector('portuguese', coalesce(content, '')),\n                'D'\n            )\n            ", persisted=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'search_vector')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'links_pages', type_='unique')
    # ### end Alembic commands ###
