"""add gin index on search_vector and drop redundant unique constraint

Revision ID: e10b72a2f417
Revises: 61b3e04d8aa6
Create Date: 2026-09-21 14:18:59.513440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e10b72a2f417'
down_revision: Union[str, Sequence[str], None] = '61b3e04d8aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('links_pages_origin_id_destiny_id_key'), 'links_pages', type_='unique')
    op.create_index('ix_pages_search_vector', 'pages', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pages_search_vector', table_name='pages', postgresql_using='gin')
    op.create_unique_constraint(op.f('links_pages_origin_id_destiny_id_key'), 'links_pages', ['origin_id', 'destiny_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
